### ISSUE TITLE
error in creating conda environment

### ISSUE THREAD

**Issue by iwansetwan** [fastscape-lem/workshop-gfz-2021-01#1]
Hi Benoit,

I have problem in creating conda environment
It said that command not found: conda
<img width="573" alt="image" src="https://user-images.githubusercontent.com/77268361/106111168-025d2680-614c-11eb-9dd4-e33aa912d05c.png">

Could you help me?

Thank you very much.

Regards,
Iwan Setiawan
PhD Researcher at Université de Rennes 1

**Comment by benbovy** [comment]
Hi Iwan, sorry I missed this issue. I guess you solved your problem last week (likely anaconda or [miniconda](https://docs.conda.io/en/latest/miniconda.html) was not yet installed) so I can close this?

**Comment by iwansetwan** [comment]
Yes
Thank you very much, Benoit!
